### ISSUE TITLE
Temperature reporting as 1200°C

### ISSUE THREAD

**Issue by mcoms** [Hotaman/OneWireSpark#1]
Hi, have you ever encountered the following behaviour with your library? It's returning > 1200°C.  It's pretty hot in the UK today, but not quite that hot :)

I'm using a Dallas `18B20` marked `1345C4 +210AA`.

```
ROM = 28 D F9 A1 5 0 0 12
  Chip = DS18B20
  Data = 1 5 4B 46 7F FF C 10 1C FF  CRC=60
  Temperature = 1200.31 Celsius, 2192.56 Fahrenheit
No more addresses.
```

An Arduino using the OneWire library with the same sensor and wiring provides:

```
ROM = 28 D F9 A1 5 0 0 12
  Chip = DS18B20
  Data = 1 D6 1 4B 46 7F FF A 10 43  CRC=43
  Temperature = 29.37 Celsius, 84.87 Fahrenheit
No more addresses.
```

I've tried using both direct and parasitic power mode (Vcc tied to Gnd, 3V3 to 4.7k resistor on DQ), with the same output.

If I remove the sensor, I just get `No more addresses.`, so I'm confident the Spark Core is receiving data. On an Arduino, CRC changes, but it seems to remain at `60` on the Spark Core.

Thanks!

**Comment by wkak** [comment]
Hi, unfortunately i have the same problem as mcoms & russgrue. Several different DS18b20 read all 1200 °C. The Rom seems to be reasonable, and the conversion from data to temp also. Heating up the sensor changes the data. 

So i guess somehow the data is messed up ?!?

Has somebody an advice for me ?!?

Thanks !

**Comment by wkak** [comment]
Hi, me again !
I have just found the solution, it was not far away:) 

Google for: 
"Remove superfluous bus writes and resets, these were causing bad temp… "

Anyhow it would be good to update the lib !

**Comment by Hotaman** [comment]
Just finished fixing and testing the DS18x20 example on the Electron. It will be posted in the next day or two.
