### ISSUE TITLE
P1 Support

### ISSUE THREAD

**Issue by BracWebb** [Hotaman/OneWireSpark#11]
Awesome this library supports the Photon -- thanks for that! I see that PLATFORM_ID with a compile error is directly handled in the header. Is there any reason that, if this library now works on the Photon (PLATFORM_ID = 6), then it cannot work on the P1 variant (PLATFORM_ID = 8). It certainly compiles and I can get around to testing it myself to verify, but thought I'd go ahead and ask since the PLATFORM_ID was not already explicitly included.

**Comment by BracWebb** [comment]
I've tested on the P1 at works just fine. As opposed to delineating by PLATFORM_ID for the fast pin access code, which results in every device needing a separate section of code that may be identical, perhaps separate by target families that require the same code, such as:
```
#if PLATFORM_ID == 0                    // Core
    #define ONEWIRE_PLATFORM_TARGET 0
#elif PLATFORM_ID == 6                  // Photon
    #define ONEWIRE_PLATFORM_TARGET 1
#elif PLATFORM_ID == 8                  // P1 (Photon Family)
    #define ONEWIRE_PLATFORM_TARGET 1
#endif

#if ONEWIRE_PLATFORM_TARGET == 0
    // Corresponding fast pin access for Core
#elif ONEWIRE_PLATFORM_TARGET == 1
    // Corresponding fast pin access for Photon Family
#endif

#else
    #error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"
#endif
```
I saw the discussion on support for the Particle Electron, not sure if the "Photon Family" code will also apply there, if so perhaps processor type or whatever HAL is appropriate would also be a good way to denote compilation targets.

**Comment by Hotaman** [comment]
I have the lib all fixed up for all platforms. Just fixing up and testing the examples. I will be updating this repo and Particle Build in the next day or two.

**Comment by Hotaman** [comment]
The lib has been updated and should work correctly on the P1. I don't have one to test with but I see no reason why it will not work as expected.
