### ISSUE TITLE
Add support for Electron

### ISSUE THREAD

**Issue by zsup** [Hotaman/OneWireSpark#12]
The Electron's not yet out, but compiling this on a prototype Electron gives me:

`*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"`

The Electron's PLATFORM_ID will be `10`, and I expect the implementation will be very similar (if not identical) to the Photon implementation.

**Comment by Hotaman** [comment]
@zsup Thanks for the heads up! I wasn't selected for the pretesting so I have to wait for the first shipment to get my hands on one. It will be needing 1-wire support for my project as well. I'll add the new platform ID. It should work fine then.

**Comment by zsup** [comment]
lemme see if I can pull some strings... ;-)

**Comment by brandoaire** [comment]
@Hotaman can you send your email and mailing address to hello@particle.io with a note that the message should be forwarded to me (Will)?  Also include your handle on our community forums if you've already created an account.

**Comment by Hotaman** [comment]
Thanks All! Almost done with the updates!
