### ISSUE TITLE
Possible issue with the protocol specs

### ISSUE THREAD

**Issue by ScruffR** [Hotaman/OneWireSpark#13]
Thanks for the contribution of the library! :+1: 

As discussed in this thread 
 https://community.particle.io/t/dallas-1-wire-onewire-lib-implementation-drive-or-float-high/19226

Could you please check if your way to drive the bus high actually conforms with the 1-wire specs?
But since you've done the port, you know best if there are reasons beyond what I saw when I looked at your code rather briefly.
In any case, just chime in on the thread linked above.

**Comment by Hotaman** [comment]
It does.

**Comment by ScruffR** [comment]
Thanks for the clear in-depth description in the thread :+1: 
So I guess closing this is the way to go.
