### ISSUE TITLE
Duo not supported

### ISSUE THREAD

**Issue by rudyv** [Hotaman/OneWireSpark#14]
HI,
I recently purchased a few DUO's from Redbear, they can be used in the Particle IDE and work fine. They combine both WiFi and BLE in almost the same footprint as the Photon.

Apperantly the Platform_ID is not a typical Particle ID and hence some code that checks the platform ID doesn't compile in the IDE.
Unfortnately also the OneWireSpak code.
Could you have a look at this ?

`OneWire/OneWire.h:121:6: error: #error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core, Photon, P1 or Electron ***"
     #error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core, Photon, P1 or Electron ***"
      ^`
KR, Rudy

**Comment by rudyv** [comment]
Hi, I just understood that the PLATFORM_ID = 88 for Duo.
Would it be possible for you to adapt the library ?
KR, Rudy

**Comment by Hotaman** [comment]
@rudyv I'll should be able to get it fixed up this coming weekend. Thank's for letting me know.

**Comment by rudyv** [comment]
@hotaman,

Many thanks, 
I like your work and sure i'll test it.
I'll be a few days of and Back next wednesday and will test later that week.
KR
Rudy

**Comment by Hotaman** [comment]
@rudyv,

No problem, Thanks for the issue on the repo! I didn't know Particle was supporting a third party product. I updated the repo yesterday so it should now work on all future products (at least until they add a new processor ;). I'll get it updated on the Particle WebIDE when I get a few minutes. Murphy has been having a hayday with me the last couple of weeks at work so I'm a little stressed at the moment.

Please let me know if you have any problems. I'll order a couple for my parts box when they are available to order. Until then I'm flying blind on this one. Thanks for offering to test it out on the DUO for me! :)
