### ISSUE TITLE
Raspberry Pi Update

### ISSUE THREAD

**Issue by sbclint** [Hotaman/OneWireSpark#19]
I hope there is still interest in this project. I have not been able to get this code to work on the Raspberry Pi.

**Comment by Hotaman** [comment]
@sbclint The 1wire lib for Particle is now a Particle supported official lib. I handed it over to them a few months ago. Please post issues to their fork of the lib or in the library forum. This is once again just my own personal version.

Support for 1wire on an RPi without extra hardware is most likely not going to happen unless you run the RPi on a non-multitasking realtime OS. While it is possible to disable all interrupts while driving the 1wire bus with software, this will cause issues with the linux OS and be unreliable. A better solution would be to use a 1wire interface chip which is accessed using the I2C or SPI interfaces available on the RPi.

**Comment by sbclint** [comment]
Thanks for the advice. That was my next approach. 
I am able to get data using Python. I confirmed that my Pi3 was seeing the DS18B20 with some Python code that was posted on AdaFruit.
see https://learn.adafruit.com/adafruits-raspberry-pi-lesson-11-ds18b20-temperature-sensing/overview. The tutorial presumes that you plug the DS18B20 into gpio 4 (AKA D0).

This successfully shows the temperature. I was going to look for a similar approach with Process control, e.g., Process::run.
