### ISSUE TITLE
Version of community library needs to be updated

### ISSUE THREAD

**Issue by dnrce** [Hotaman/OneWireSpark#3]
When using the Spark community version of the library, I get errors about the `FALSE` definition (fixed in cec378824e1e7fa72834a7938f0e98c88f441d9f), but I don't when I use my own identical fork. I suspect Spark needs to be told to reimport the library.

**Comment by CptanPanic** [comment]
Any update on this?  I see the json is stating the version should be 1.1.0, but the one on particle.io is only 1.0.0  Maybe the json is not quite correct?

**Comment by Hotaman** [comment]
sorry I didn't close this already. it is fixed.
