### ISSUE TITLE
'PIN_MAP' was not declared in this scope

### ISSUE THREAD

**Issue by e-coucou** [Hotaman/OneWireSpark#8]
Veryfing code using this library in Particle Build fails with this error:
```
OneWire/OneWire.cpp:142:1: error: 'PIN_MAP' was not declared in this scope
 PIN_MAP[_pin].gpio_peripheral->BRR = PIN_MAP[_pin].gpio_pin

**Comment by joltup** [comment]
Same here.

**Comment by GregSawin** [comment]
There's a newer version of the library for Particle, just remove the old library and add the new one (v1.1.0) and the problem goes away.

**Comment by e-coucou** [comment]
kool! many thanks

**Comment by Hotaman** [comment]
Thanks for confirming last update!
