### ISSUE TITLE
'GPIO_TypeDef' was not declared in this scope

### ISSUE THREAD

**Issue by gyengus** [Hotaman/OneWireSpark#9]
Veryfing code using this library in Particle Build fails with this error:
```
OneWire/OneWire.cpp:146:1: error: 'GPIO_TypeDef' was not declared in this scope
 GPIO_TypeDef *gpio_port = PIN_MAP[_pin].gpio_peripheral

**Comment by gyengus** [comment]
I have Particle Photon.

**Comment by Hotaman** [comment]
Should have been fixed in the last update. I'll make sure to test the latest version this weekend in Build.
